[theme]
primaryColor = "#F17216"        # Couleur d'accentuation
backgroundColor = "#FFFFFF"     # Couleur de fond principale
secondaryBackgroundColor = "#F0F2F6" # Couleur de la barre latérale
textColor = "#262730"           # Couleur du texte
font = "sans serif"             # Police de caractères
